POST http://localhost:4200/api/nutritional-plan/ 
Content-Type: application/json; charset=utf-8

{
    "planName": "Mi plan",
    "planType": "Perdida de Peso",
    "startDate": "2024-02-01",
    "endDate": "2024-04-15",
    "status": "active",
    "calories": "2000",
    "breakfast": "algo",
    "lunch": "algo",
    "dinner": "algo",
    "snacks": "algo",
    "userId": "2"
}

